Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -48,3 +48,12 @@ jobs:
         git commit -m "Add CSV file generated by scraper"
         git push https://${{ secrets.GIT_USER_NAME }}:${{ secrets.PAT }}@github.com/ezrarichard/Football-Scraper.git
  
+    - name: Download CSV File
+      run: |
+        if curl -o all_leagues_2023_2024.csv -u "${{ secrets.GIT_USER_NAME }}:${{ secrets.GITHUB_TOKEN }}" "https://raw.githubusercontent.com/ezrarichard/Football-Scraper/main/all_leagues_2023_2024.csv"; then
+        echo "CSV download successful."
+        else
+          echo "CSV download failed."
+          exit 1
+        fi
+        
